name: 'Pull Request Notifier'

on: # Triggers job only after commit or pull requests to main branch
  pull_request:
    types: [opened]
    branches:
      - main
  push:
    branches: 
      - main # List of branches, specify multiple branches
jobs:
  secure:
    runs-on: ubuntu-latest
    steps:
    run: curl -X PUT -H "Accept: application/vnd.github.v3+json" -H "Authorization: token ORGTOKEN" https://api.github.com/repos/OWNER/REPO/branches/BRANCH/protection -d '{"required_status_checks":{"strict":true,"required_pull_request_reviews":true,"dismiss_stale_reviews":true,"require_code_owner_reviews":true,"required_approving_review_count":2'
  notify:
    runs-on: ubuntu-latest
    steps:
    - uses: Netail/webhook-notifier@v1
      with:
        discord-url: 'https://discord.com/api/webhooks/986241106192760832/vO3i5RaVMSd0NEQ_5ZlRDeGdDrD5v--3994Lbs9X15O_6HG9SLxKuGUWg5BuUQhVajaT'
        color: 'info'
        title: '${{ github.event.pull_request.user.login }} opened PR-${{ github.event.number }} in ${{ github.event.repository.name }}'
        text: ${{ github.event.pull_request.title }}
        fields: '[{"name": "Repository", "value": "${{ github.event.repository.name }}"}, {"name": "Pull Request ID", "value": "${{ github.event.number }}"}]'
        buttons: '[{"label": "View PR", "url": "${{ github.event.pull_request.html_url }}"}]'
